export const coffees = [
  {
    id: "blanco-1",
    name: "Arundaya Double Wash",
    company: "Blanco Coffee Roaster",
    price: 110000,
    description: {
      origin: "Pantan Musara, Aceh Gayo",
      altitude: "1.650 mdpl",
      varietas: "Single Varietas (Abyssinia)",
      process: "Double Washed",
      roasting: "Filter Roast",
      notes: "Vanilla Aroma, Green Apple, Rounded Body, Caramel Finish",
    },
    isRecommended: true,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/blanco1.jpg",
  },
  {
    id: "blanco-2",
    name: "Arundaya Giling Basah",
    company: "Blanco Coffee Roaster",
    price: 90000,
    description: {
      origin: "Pantan Musara, Aceh Gayo",
      altitude: "1.650 mdpl",
      varietas: "Abyssinia, Catura, Bourbon",
      process: "Giling Basah (Wet Hulled)",
      roasting: "Filter Roast",
      notes: "Mapple Syrup Aroma, Passion Fruit, Smooth Body, Black Tea Finish",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: true,
    weight: "200 gram",
    imageUrl: "/images/blanco2.jpg",
  },
  {
    id: "blanco-3",
    name: "Ijen Madu Merah",
    company: "Blanco Coffee Roaster",
    price: 95000,
    description: {
      origin: "Banyuwangi, Mt. Ijen, East Java",
      altitude: "1110 - 1200 mdpl",
      varietas: "Cobra, USDA 762, Lini S",
      process: "Red Honey",
      roasting: "Filter Roast",
      notes:
        "Oolong Tea Aroma, Palm Sugar, syrupy body with hints of chocolate",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/blanco3.jpg",
  },
  {
    id: "blanco-4",
    name: "Mamasa Sumarorong",
    company: "Blanco Coffee Roaster",
    price: 90000,
    description: {
      origin: "Mamasa, Sumarorong, West Sulawesi",
      altitude: "1200 - 1300 mdpl",
      varietas: "Typica, Lini S",
      process: "Wet Hulled",
      roasting: "Filter Roast",
      notes: "Ginger Aroma, Pomelo, creamy body with hints of Molases",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/blanco4.jpg",
  },
  {
    id: "blanco-5",
    name: "Orwell - Espresso Blend Arabica",
    company: "Blanco Coffee Roaster",
    price: 285000,
    description: {
      origin: "Pantan Musara, Aceh Gayo",
      altitude: "1.650 mdpl",
      varietas: "Mixed",
      process: "Double Washed",
      roasting: "Espresso Roast - Double Roasting Profile",
      notes:
        "Black: Mandarin Orange, Caramel, Medium Body, Floral Finish - White: Vanilla Biscuit, Brown Sugar, White Chocolate",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "1 kilogram",
    imageUrl: "/images/blanco5.jpg",
  },
  {
    id: "blanco-6",
    name: "Blanco Coffee Drip Bag - Single Origin Gayo",
    company: "Blanco Coffee Roaster",
    price: 65000,
    extras: `Di dalam 1 kemasan Pouch drip bag ini terdapat 5 varian kopi yang berasal dari kebun kami, Aceh, Gayo. Dengan 5 jenis processing method, diantaranya: Arundaya Natural, Arundaya Anaerob Honey, Arundaya Double Wash, Arundaya Full Wash, Arundaya Giling Basah`,
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "5 sachet @20 gram",
    imageUrl: "/images/blanco6.jpg",
  },
  {
    id: "djaya-1",
    name: "Sunda Patuha Yeast Natural Lot #1",
    company: "Djaya Coffee Roasters",
    price: 100000,
    description: {
      origin: "Gn. Patuha, Rancabali, Alamendah, Bandung, Jawa Barat",
      altitude: "1600 mdpl",
      varietas: "Ateng Super",
      process: "Yeast Natural",
      roasting: "Light",
      notes: "Rosebud, Raspberry & Honey",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/djaya1.jpg",
  },
  {
    id: "djaya-2",
    name: "Gayo Pantan Musara CM Honey",
    company: "Djaya Coffee Roasters",
    price: 100000,
    description: {
      origin: "Pantan Musara, Aceh Gayo",
      altitude: "1670 mdpl",
      varietas: "Abyssinia, Caturra, Catimor",
      process: "Honey Carbonic Maceration (CM)",
      roasting: "Light",
      notes: "Honey, Cherry, Passion Fruit",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: true,
    weight: "200 gram",
    imageUrl: "/images/djaya2.jpg",
  },
  {
    id: "djaya-3",
    name: "Gayo Madu Musara",
    company: "Djaya Coffee Roasters",
    price: 100000,
    description: {
      origin: "Pantan Musara, Aceh Gayo",
      altitude: "1670 mdpl",
      varietas: "Abyssinia & P-88",
      process: "Honey",
      roasting: "Light",
      notes: "Apple, Molasses & White Tea",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/djaya3.jpg",
  },
  {
    id: "djaya-4",
    name: "Toraja Pulu' Pulu",
    company: "Djaya Coffee Roasters",
    price: 100000,
    description: {
      origin: "Pulu' Pulu, Buntu Pepasan, Sulawesi Selatan",
      altitude: "1200 - 1500 mdpl",
      varietas: "S-795",
      process: "Washed",
      roasting: "Half City",
      notes: "Molasses, Blackcurrant & Jasmine Tea",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/djaya4.jpg",
  },
  {
    id: "djaya-5",
    name: "Bali Satra Washed",
    company: "Djaya Coffee Roasters",
    price: 85000,
    description: {
      origin: "Satra, Kintamani, Bali",
      altitude: "1250 mdpl",
      varietas: "Kopyol (B-1)",
      process: "Washed",
      roasting: "Half City",
      notes: "Molasses, Sweet Lime & hints of Jasmine",
    },
    isRecommended: false,
    isTerbaru: true,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/djaya5.jpg",
  },
  {
    id: "epic-1",
    name: "Malabar Java Natural",
    company: "Epic Coffee",
    price: 130000,
    description: {
      origin: "Pangalengan, West Java, Indonesia",
      altitude: "1400 mdpl",
      varietas: "Sigararutang, Andungsari",
      process: "Natural",
      roasting: "Medium Roast",
      notes: "Sweet Honey, Mango, Medium Body, Clean After Taste",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: true,
    weight: "200 gram",
    imageUrl: "/images/epic1.jpg",
  },
  {
    id: "epic-2",
    name: "Ijen Peaberry",
    company: "Epic Coffee",
    price: 150000,
    description: {
      origin: "MT. Argopuro, Bondowoso, Indonesia",
      altitude: "1200-1400 mdpl",
      varietas: "S795, Andungsari",
      process: "Natural",
      roasting: "Medium Roast",
      notes:
        "Grape, Manggo, Orange, Hint of Cinnamon, Good Body and Smooth After Taste",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/epic2.jpg",
  },
  {
    id: "epic-3",
    name: "Luwak Gayo",
    company: "Epic Coffee",
    price: 320000,
    description: {
      origin: "Gayo, Aceh, Indonesia",
      altitude: "1400 mdpl",
      varietas: "Bourbon",
      process: "Washed",
      roasting: "Medium Roast",
      notes: "Spicy, Citrus, Caramel, Choco, Medium Body and Long After Taste",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/epic3.jpg",
  },
  {
    id: "epic-4",
    name: "90+ Areka Yirgacheffe Ethiopia",
    company: "Epic Coffee",
    price: 190000,
    description: {
      origin: "Yirgacheffe, Ethiopia",
      altitude: "1950 mdpl",
      varietas: "Hairloom",
      process: "Natural",
      roasting: "Medium Roast",
      notes:
        "Floral Bomb, an Ethiopia Extraordinary Lot, This is an Intense Floral Bomb, Clean Coffee with Berry Aromatic, Candy Sweetness and Deep Flavour Note of Jasmine, Plum, Lemon and Blackcurrant",
    },
    isRecommended: true,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/epic4.jpg",
  },
  {
    id: "epic-5",
    name: "90+ Metis Espresso Blend",
    company: "Epic Coffee",
    price: 450000,
    description: {
      origin: "Guji Ethiopia, Ethiopia Kochere, Columbia",
      altitude: "1300 - 1900 mdpl",
      varietas: "Mix",
      process: "natural, washed ",
      roasting: "Medium Roast",
      notes:
        "Espresso: Fruit Bomb of Peach,Citrus, Strawberry and Jasmine Light Body with Long Sweet Finish - Milk Based: Very Sweet with Flavour of Almound, Apricot and Jasmine",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "1 kilogram",
    imageUrl: "/images/epic5.jpg",
  },
  {
    id: "imba-1",
    name: "Kaba Lesmana Semi Washed",
    company: "IMBA Coffee",
    price: 95000,
    description: {
      origin: "Gunung Kaba - Bengkulu",
      altitude: "1100 - 1300 mdpl",
      varietas: "Sigararutang",
      process: "Semi Washed",
      roasting: "Medium Roast",
      notes: "Apricot . Chocolate . Caramel",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/imba1.jpg",
  },
  {
    id: "imba-2",
    name: "Bondo Argopuro Natural",
    company: "IMBA Coffee",
    price: 95000,
    description: {
      origin: "Gunung Argopuro - Pokmas Walida - Jawa Timur",
      altitude: "1200 - 1400 mdpl",
      varietas: "Lini S & Kartika",
      process: "Natural",
      roasting: "Light to Medium",
      notes: "Orange . Molasses . Banana",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: true,
    weight: "200 gram",
    imageUrl: "/images/imba2.jpg",
  },
  {
    id: "imba-3",
    name: "Pak Haji Van Halu Natural",
    company: "IMBA Coffee",
    price: 95000,
    description: {
      origin: "Gunung Halu - Jawa Barat",
      altitude: "1200 - 1300 mdpl",
      varietas: "Typica",
      process: "Natural",
      roasting: "Medium Roast",
      notes: "Black Tea . Winey . Banana",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/imba3.jpg",
  },
  {
    id: "imba-4",
    name: "Simalungun Na Birong Semi Washed",
    company: "IMBA Coffee",
    price: 95000,
    description: {
      origin: "Simalungun - Sumatera Utara",
      altitude: "1100 - 1300mdpl",
      varietas: "Sigararutang",
      process: "Semi Washed",
      roasting: "Medium Roast",
      notes: "Orange Peel . Cinnamon . Earthy",
    },
    isRecommended: false,
    isTerbaru: true,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/imba4.jpg",
  },
  {
    id: "maige-1",
    name: "Batak Lumban Julu",
    company: "Maige Coffee Roastery",
    price: 80000,
    description: {
      origin: "Lumban Julu, Humbahas",
      altitude: "1550 mdpl",
      varietas: "Sigarar Utang & Atenf",
      process: "Wet Hulled",
      roasting: "Light to Medium",
      notes: "Berry, molases, citrus",
    },
    isRecommended: false,
    isTerbaru: true,
    isPilihan: false,
    weight: "250 gram",
    imageUrl: "/images/maige1.jpg",
  },
  {
    id: "maige-2",
    name: "Gambung Pasir Jambu",
    company: "Maige Coffee Roastery",
    price: 85000,
    description: {
      origin: "Pasir Jambu, Gambung, Bandung",
      altitude: "1350 mdpl",
      varietas: "Andungsari & Sigararutang",
      process: "Full Washed",
      roasting: "Light to Medium",
      notes: "Lemon, mango, clean aftertaste",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "250 gram",
    imageUrl: "/images/maige2.jpg",
  },
  {
    id: "maige-3",
    name: "Gayo USDA Dry Hull",
    company: "Maige Coffee Roastery",
    price: 90000,
    description: {
      origin: "Wih Pesam, Simpang Teritit, Aceh Gayo",
      altitude: "1600 mdpl",
      varietas: "USDA 762",
      process: "Washed Dry Hull",
      roasting: "Medium",
      notes: "Citrus, blueberry, green tea aroma",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "250 gram",
    imageUrl: "/images/maige3.jpg",
  },
  {
    id: "lestari-1",
    name: "Wonosobo Natural",
    company: "Lestari Coffee Roasters",
    price: 100000,
    description: {
      origin: "Wonosobo, Central Java",
      altitude: "1600",
      varietas: "Kartika",
      process: "Natural",
      roasting: "Medium",
      notes: "apple tea, lemon zest, sugarcane juice",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: true,
    weight: "200 gram",
    imageUrl: "/images/lestari1.jpg",
  },
  {
    id: "lestari-2",
    name: "Kamojang Full Washed",
    company: "Lestari Coffee Roasters",
    price: 95000,
    description: {
      origin: "Kamojang, West Java",
      altitude: "1600-1800 mdpl",
      varietas: "USDA, Lini S, Sigararutang",
      process: "Full washed",
      roasting: "Medium",
      notes: "lime, starfruit, oolong tea",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/lestari2.jpg",
  },
  {
    id: "lestari-3",
    name: "Gayo Kenawat Black Honey",
    company: "Lestari Coffee Roasters",
    price: 100000,
    description: {
      origin: "Kampung Kenawat, North Sumatera",
      altitude: "1300-1700 mdpl",
      varietas: "Typica, Ateng, Timtim",
      process: "Black Honey",
      roasting: "Light to Medium",
      notes: "black tea, green apple, lime",
    },
    isRecommended: false,
    isTerbaru: true,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/lestari3.jpg",
  },
  {
    id: "lestari-4",
    name: "Argopuro Natural",
    company: "Lestari Coffee Roasters",
    price: 120000,
    description: {
      origin: "Argopuro, East Java",
      altitude: "1200-1400 mdpl",
      varietas: "Lini S795, Kartika",
      process: "Natural",
      roasting: "Light",
      notes: "red apple, banana-like, juicy",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/lestari4.jpg",
  },
  {
    id: "riphy-1",
    name: "Robusta Jepalo",
    company: "Riphy Coffee Roastery",
    price: 150000,
    description: {
      origin: "Desa Jepalo, Pati, Jawa Tengah",
      altitude: "700 - 900 Mdpl",
      varietas: "Tugusari - Mix",
      process: "Natural",
      roasting: "Medium - Dark",
      notes: "Sweet dark chocolate",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "1 kilogram",
    imageUrl: "/images/riphy1.jpg",
  },
  {
    id: "riphy-2",
    name: "Bone - Bone Enrekang",
    company: "Riphy Coffee Roastery",
    price: 90000,
    description: {
      origin: "Enrekang, Sulawesi Selatan",
      altitude: "900 - 1200 Mdpl",
      varietas: "Mix varietas",
      process: "Semi washed",
      roasting: "Light - Medium",
      notes: "Lemon, Pomegranate, Butter scotch",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/riphy2.jpg",
  },
  {
    id: "riphy-3",
    name: "Gayo Araishien",
    company: "Riphy Coffee Roastery",
    price: 95000,
    description: {
      origin: "Gayo Pegasing, Aceh",
      altitude: "900 - 1100 Mdpl",
      varietas: "Mix varietas",
      process: "Natural",
      roasting: "Light - Medium",
      notes: "Green Apple, Honey Tea, dan Maple syrup",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/riphy3.jpg",
  },
  {
    id: "space-1",
    name: "Strawberry Fields - Espresso Blend Arabika",
    company: "Space Coffee Roastery",
    price: 100000,
    description: {
      origin: "Bali and Aceh",
      altitude: "1100 - 1400 mdpl",
      varietas: "Mix",
      process: "Natural, Full Washed",
      roasting: "Espresso Roast",
      notes: "Strawberry, Apricot, Vanilla, Lemon Zest, Hint of Coffee Pulp",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/space1.jpg",
  },
  {
    id: "space-2",
    name: "Originutt - Espresso Blend Arabika",
    company: "Space Coffee Roastery",
    price: 100000,
    description: {
      origin: "Brazil, Bali, Aceh",
      altitude: "1200 - 1500 mdpl",
      varietas: "Mix",
      process: "Semi Washed, Red Honey, Natural",
      roasting: "Espresso Roast",
      notes:
        "Nougat, Green Apple, Apricot, Raw Honey, Liquorice, Roasted Peanut",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/space2.jpg",
  },
  {
    id: "space-3",
    name: "Gayo Black Tea",
    company: "Space Coffee Roastery",
    price: 85000,
    description: {
      origin: "Pegasing, Gayo, Aceh",
      altitude: "1250 mdpl",
      varietas: "Tim-Tim & Bourbon",
      process: "Wet Hull",
      roasting: "Filter Roast",
      notes: "Black Tea, Apricot, Overall Sweetness",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/space3.jpg",
  },
  {
    id: "space-4",
    name: "Lintong Green Mango",
    company: "Space Coffee Roastery",
    price: 135000,
    description: {
      origin: "Lintongnihuta, North Sumatera",
      altitude: "1400-1450 mdpl",
      varietas: "Sigararutang",
      process: "Anaerobic Yeast Fermentation",
      roasting: "Filter Roast",
      notes:
        "Green Mango, Tomato, Cranberry, White Chocolate, Cinnamon, Ginger",
    },
    isRecommended: true,
    isTerbaru: false,
    isPilihan: false,
    weight: "200 gram",
    imageUrl: "/images/space4.jpg",
  },
  {
    id: "space-5",
    name: "Rancabali Peach",
    company: "Space Coffee Roastery",
    price: 135000,
    description: {
      origin: "Rancabali, West Java",
      altitude: "1300-1500 mdpl",
      varietas: "Sigararutang, Lini-S",
      process: "Natural",
      roasting: "Filter Roast",
      notes: "Peach, Black Tea, Mango, Molasses, Caramel, Hint of Strawberry",
    },
    isRecommended: false,
    isTerbaru: false,
    isPilihan: true,
    weight: "200 gram",
    imageUrl: "/images/space5.jpg",
  },
];

export function getCoffee(id) {
  return coffees.find((c) => c.id === id);
}

export function getRecommended() {
  return coffees.filter((c) => c.isRecommended === true);
}

export function getTerbaru() {
  return coffees.filter((c) => c.isTerbaru === true);
}

export function getPilihan() {
  return coffees.filter((c) => c.isPilihan === true);
}
